name: Pull requests

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.MD'
    branches:
      - 'master'
      - 'pivotlayoutmanager'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4

      - name: Run unit tests
        run: ./gradlew --build-cache testDebugUnitTest --stacktrace

      - name: Assemble library
        run: ./gradlew --build-cache assembleRelease

  ui_test:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        arch: [ x86 ]
        target: [ android-tv ]
        api-level: [28]
        profile: [tv_1080p]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: UI Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: ${{ matrix.profile }}
          force-avd-creation: false
          disable-animations: false
          avd-name: avd-28
          cores: 4
          disk-size: 6096M
          ram-size: 4096M
          emulator-options: -no-window -no-snapshot -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: ./gradlew --build-cache connectedDebugAndroidTest --info

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.api-level }}-${{ matrix.arch }}-instrumentation-test-results
          path: |
            ./**/build/reports/androidTests/connected/**
            ./**/build/outputs/connected_android_test_additional_output/debugAndroidTest/connected/**
        if: always()